version: '3.4'

services:
  redrift_test_backend.core:
    image: ${DOCKER_REGISTRY-}redrifttestbackendcore
    build:
      context: .
      dockerfile: RedRift_Test_Backend.Core/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "zfC5h0uZ"
      ACCEPT_EULA: "Y"
  client:
    image: emin2105/redrift-test-client
    depends_on:
      - redrift_test_backend.core